title: Adrian Mui
description: My Personal Website
author: Adrian Mui
logo: https://scontent.xx.fbcdn.net/v/t1.0-9/13256416_10209746053826842_4045384163178443016_n.jpg?oh=ef49f80d2664f11dafca67339259dba9&oe=5870872A
github: https://github.com/adrianmui
about: Full Stack Developer

baseurl: ""
url: "https://adrianmui.github.io/"

disqus_shortname: aboutashu
google_analytics: UA-72862926-1

share:
  twitter_username: \#
  fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
